naming:
  strip-prefixes:
    - JPH_PhysicsUpdateError_
    - JPH_BodyType_
    - JPH_MotionType_
    - JPH_Activation_
    - JPH_ValidateResult_
    - JPH_ShapeType_
    - JPH_ShapeSubType_
    - JPH_ConstraintType_
    - JPH_ConstraintSubType_
    - JPH_ConstraintSpace_
    - JPH_MotionQuality_
    - JPH_OverrideMassProperties_
    - JPH_AllowedDOFs_
    - JPH_GroundState_
    - JPH_BackFaceMode_
    - JPH_ActiveEdgeMode_
    - JPH_CollectFacesMode_
    - JPH_MotorState_
    - JPH_CollisionCollectorType_
    - JPH_SwingType_
    - JPH_SixDOFConstraintAxis_
    - JPH_SpringMode_
    - JPH_SoftBodyConstraintColor_
    - JPH_SoftBodyBendType_
    - JPH_BodyManager_ShapeColor_
    - JPH_DebugRenderer_CastShadow_
    - JPH_DebugRenderer_DrawMode_
    - JPH_Mesh_Shape_BuildQuality_
    - JPH_TransmissionMode_
    - JPH_TrackSide_
    - JPH_DebugRenderer_
    - JPH_BodyDrawFilter_
    - JPH_BodyActivationListener_
    - JPH_ContactListener_
    - JPH_PhysicsStepListener_
    - JPH_CharacterVsCharacterCollision_
    - JPH_CharacterVsCharacterCollisionSimple_
    - JPH_CharacterContactListener_
    - JPH_BodyFilter_
    - JPH_BroadPhaseLayerFilter_
    - JPH_SimShapeFilter_
    - JPH_ShapeFilter_
    - JPH_ObjectLayerFilter_
    - JPH_PhysicsMaterial_
    - JPH_MotionProperties_
    - JPH_MassProperties_
    - JPH_ContactManifold_
    - JPH_WheeledVehicleControllerSettings_
    - JPH_WheeledVehicleController_
    - JPH_WheelWV_
    - JPH_WheelTV_
    - JPH_WheelSettingsWV_
    - JPH_WheelSettingsTV_
    - JPH_Wheel_
    - JPH_WheelSettings_
    - JPH_VehicleTransmissionSettings_
    - JPH_VehicleTransmission_
    - JPH_VehicleTrackSettings_
    - JPH_VehicleTrack_
    - JPH_VehicleEngine_
    - JPH_VehicleEngineSettings_
    - JPH_VehicleDifferentialSettings_
    - JPH_VehicleController_
    - JPH_VehicleControllerSettings_
    - JPH_VehicleCollisionTesterRay_
    - JPH_VehicleCollisionTesterCastSphere_
    - JPH_VehicleCollisionTesterCastCylinder_
    - JPH_VehicleCollisionTester_
    - JPH_VehicleAntiRollBar_
    - JPH_TrackedVehicleControllerSettings_
    - JPH_TrackedVehicleController_
    - JPH_MotorcycleControllerSettings_
    - JPH_MotorcycleController_
    - JPH_LinearCurve_
    - JPH_TriangleShapeSettings_
    - JPH_TriangleShape_
    - JPH_TaperedCylinderShapeSettings_
    - JPH_TaperedCylinderShape_
    - JPH_TaperedCapsuleShapeSettings_
    - JPH_TaperedCapsuleShape_
    - JPH_StaticCompoundShapeSettings_
    - JPH_StaticCompoundShape_
    - JPH_SphereShapeSettings_
    - JPH_SphereShape_
    - JPH_ShapeSettings_
    - JPH_Shape_
    - JPH_ScaledShapeSettings_
    - JPH_ScaledShape_
    - JPH_RotatedTranslatedShapeSettings_
    - JPH_RotatedTranslatedShape_
    - JPH_PlaneShapeSettings_
    - JPH_PlaneShape_
    - JPH_OffsetCenterOfMassShapeSettings_
    - JPH_OffsetCenterOfMassShape_
    - JPH_MutableCompoundShapeSettings_
    - JPH_MutableCompoundShape_
    - JPH_MeshShape_
    - JPH_MeshShapeSettings_
    - JPH_HeightFieldShapeSettings_
    - JPH_HeightFieldShape_
    - JPH_EmptyShapeSettings_
    - JPH_EmptyShape_
    - JPH_DecoratedShape_
    - JPH_CylinderShapeSettings_
    - JPH_CylinderShape_
    - JPH_ConvexShapeSettings_
    - JPH_ConvexShape_
    - JPH_ConvexHullShapeSettings_
    - JPH_ConvexHullShape_
    - JPH_CompoundShapeSettings_
    - JPH_CompoundShape_
    - JPH_CapsuleShapeSettings_
    - JPH_CapsuleShape_
    - JPH_BoxShapeSettings_
    - JPH_BoxShape_
    - JPH_ShapeSettings_
    - JPH_Shape_
    - JPH_CollideShapeSettings_
    - JPH_ShapeCastSettings_
    - JPH_SkeletonMapper_
    - JPH_Skeleton_
    - JPH_SkeletalAnimation_
    - JPH_RagdollSettings_
    - JPH_Ragdoll_
    - JPH_NarrowPhaseQuery_
    - JPH_BroadPhaseQuery_
    - JPH_ObjectVsBroadPhaseLayerFilterTable_
    - JPH_ObjectVsBroadPhaseLayerFilterMask_
    - JPH_ObjectVsBroadPhaseLayerFilter_
    - JPH_ObjectLayerPairFilterTable_
    - JPH_ObjectLayerPairFilterMask_
    - JPH_ObjectLayerPairFilter_
    - JPH_Math_
    - JPH_Quat_
    - JPH_Vec3_
    - JPH_Mat4_
    - JPH_JobSystemThreadPool_
    - JPH_JobSystemCallback_
    - JPH_JobSystem_
    - JPH_GroupFilter_
    - JPH_GroupFilterTable_
    - JPH_VehicleConstraintSettings_
    - JPH_VehicleConstraint_
    - JPH_TwoBodyConstraint_
    - JPH_SwingTwistConstraintSettings_
    - JPH_SwingTwistConstraint_
    - JPH_SwingTwistConstraint_
    - JPH_SliderConstraintSettings_
    - JPH_SliderConstraint_
    - JPH_SixDOFConstraintSettings_
    - JPH_SixDOFConstraintSettings_Init
    - JPH_SixDOFConstraint_
    - JPH_PointConstraintSettings_
    - JPH_PointConstraint_
    - JPH_HingeConstraintSettings_
    - JPH_HingeConstraint_
    - JPH_GearConstraintSettings_
    - JPH_GearConstraint_
    - JPH_FixedConstraintSettings_
    - JPH_FixedConstraint_
    - JPH_DistanceConstraintSettings_
    - JPH_DistanceConstraint_
    - JPH_ConeConstraintSettings_
    - JPH_ConeConstraint_
    - JPH_Constraint_
    - JPH_CharacterSettings_
    - JPH_CharacterVirtualSettings_
    - JPH_CharacterVirtual_
    - JPH_Character_
    - JPH_CharacterBase_
    - JPH_PhysicsSystem_
    - JPH_BroadPhaseLayerInterface_
    - JPH_BroadPhaseLayerInterfaceMask_
    - JPH_BroadPhaseLayerInterfaceTable_
    - JPH_SoftBodySharedSettings_
    - JPH_SoftBodyCreationSettings_
    - JPH_BodyCreationSettings_
    - JPH_BodyInterface_
    - JPH_BodyLockInterface_
    - JPH_BodyLockMultiRead_
    - JPH_BodyLockMultiWrite_
    - JPH_Body_
    - JPH_
  strip-postfixes:
