# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "Overhaul" ]
  pull_request:
    branches: [ "Overhaul" ]

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - name: Set up JDK 26
      uses: actions/setup-java@v5
      with:
        java-version: '26'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Execute the HelloWorld app
      run: |
        $JAVA_HOME/bin/java --enable-preview --enable-native-access=ALL-UNNAMED \
          -cp target/JoltPhysics-JavaFFM-5.5.0-jar-with-dependencies.jar \
          volucris.bindings.jolt.HelloWorld

  macOS:
    runs-on: macos-26
    steps:
    - uses: actions/checkout@v7
    - name: Set up JDK 26
      uses: actions/setup-java@v5
      with:
        java-version: '26'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Execute the HelloWorld app
      run: |
        $JAVA_HOME/bin/java --enable-preview --enable-native-access=ALL-UNNAMED \
          -cp target/JoltPhysics-JavaFFM-5.5.0-jar-with-dependencies.jar \
          volucris.bindings.jolt.HelloWorld

  Windows:
    runs-on: windows-2025
    steps:
    - uses: actions/checkout@v7
    - name: Set up JDK 26
      uses: actions/setup-java@v5
      with:
        java-version: '26'
        distribution: 'oracle'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      shell: bash
    - name: Execute the HelloWorld app
      run: |
        "$JAVA_HOME/bin/java" --enable-preview --enable-native-access=ALL-UNNAMED \
          -cp target/JoltPhysics-JavaFFM-5.5.0-jar-with-dependencies.jar \
          volucris.bindings.jolt.HelloWorld
      shell: bash
