class-description:
  name: CharacterContactSettings
  package-name: volucris.bindings.jolt.character
  directory: src/main/java/volucris/bindings/jolt/character
  is-static: false
  parent:
  parent-has-segment-constructor: false
  interfaces: []
  is-sealed: false
  permits: []
  is-abstract: false
  is-final: true
  instance-parameter:

imports:
static-imports:
  - java.lang.foreign.ValueLayout.*

macro-name-prefixes:
excluded-macro-name-prefixes:
macro-names:
excluded-macro-names:

symbol-prefixes:
symbols:

function-name-prefixes:
excluded-function-name-prefixes:
function-name-postfixes:
excluded-function-name-postfixes:

constructors:
struct:
  name: JPH_CharacterContactSettings
native-functions:
native-function-pointers: